language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
# uncomment this line if your project needs to run something other than `rake`:
install: bundle exec rake db:migrate
script: bundle exec rspec
